Lesson8 try1
DavydovaVV/repo-java pull request #11
Opened 2021-04-19 12:13 UTC by DavydovaVV

2021-04-19 19:03 UTC, tlt-java-courses requested changes
Замечания
- Неправильный формат пути пакетов
- Наличие пустого файла debug.log в репозитории. Добавляй в гитигнор.
- Отсутствие логгирования в коде
- Форматирование
  - Наличие пустых строк после JavaDoc.
- По коду
  - Использование Raw типа
- JavaDoc
  - Отсутствие JavaDoc на публичных классах.   

Рекомендации
- В ряде мест можно было использовать lombok

2021-04-19 19:03 UTC, tlt-java-courses commented on src/main/java/davydova/files/Cache.java
> +        CacheElement<T> cacheElement = null;
Зачем объявлять переменную здесь, если используется она только в if ниже?

2021-04-19 21:45 UTC, DavydovaVV commented on src/main/java/davydova/files/Cache.java
> +        CacheElement<T> cacheElement = null;
Убрала, просто я тогда не знала, что можно выбросить исключение вместо null и не догадалась, что можно просто return null сделать

2021-04-20 13:17 UTC, DavydovaVV commented on src/main/java/davydova/files/Cache.java
> +        CacheElement<T> cacheElement = null;
> Неправильный формат пути пакетов
Сделала отдельный пакет для Exceptions

> Наличие пустого файла debug.log в репозитории. Добавляй в гитигнор.
Сначала добавила в гитигнор всю папку, потом вообще её удалила, т.к. сделала логирование в консоль

> Отсутствие логгирования в коде
Сделала логирование

> Форматирование
Наличие пустых строк после JavaDoc.
Убрала

> По коду
Использование Raw типа
Я использовала массив типа Object, чтобы иметь возможность записать массив типа T в массив типа Storage<T>. Если не использовать raw тип, то я не смогу этого сделать
![image](https://user-images.githubusercontent.com/81247195/115401906-f7baa680-a1fb-11eb-8193-342875535b87.png)

> JavaDoc
Отсутствие JavaDoc на публичных классах.
Добавила JavaDoc для класса CacheElement, у которого он отсутствовал

> В ряде мест можно было использовать lombok
Использовала аннотацию @Data и убрала getters для полей классов

2021-04-20 19:57 UTC, tlt-java-courses approved these changes

2021-04-20 19:57 UTC, tlt-java-courses commented on src/main/java/davydova/files/Cache.java
> +package davydova.files;
Неправильныйы формат пути. Пути пакетов должны быть в формате обратного доменного имени. Напр. `com.epam.davydova`

2021-04-20 19:57 UTC, tlt-java-courses commented on src/main/java/davydova/files/Main.java
> +        storage1.getCache().add("3",2);
Если запустить этот метод, то в логах одно info.

2021-04-20 19:57 UTC, tlt-java-courses commented on src/main/java/davydova/files/Storage.java
> +        log.info("Method add(T) of class Storage");
Причем что здесь это ещё нормально что info, но не хватает передаваемого в метод объекта.

2021-04-20 19:57 UTC, tlt-java-courses commented on src/main/java/davydova/files/Storage.java
> +        log.info("Array storage before adding element: {}", Arrays.toString(storage));
А это можно уже в дебаг убрать.

2021-04-20 19:57 UTC, tlt-java-courses commented on src/main/java/davydova/files/exceptions/ArrayNullPointerException.java
> +
Перенос

2021-04-20 19:57 UTC, tlt-java-courses commented on src/test/java/davydova/files/CacheTest.java
> +public class CacheTest<T> {
JavaDoc?

2021-04-20 19:57 UTC, tlt-java-courses commented on src/test/java/davydova/files/StorageTest.java
> +public class StorageTest {
JavaDoc?

2021-04-20 19:57 UTC, merged