Changed project structure, added classes to implement lesson9 assignm…
DavydovaVV/repo-java pull request #12
Opened 2021-04-21 21:04 UTC by DavydovaVV

Changed project structure, added classes to implement lesson9 assignment up to **

2021-04-22 06:54 UTC, tlt-java-courses requested changes

2021-04-22 06:54 UTC, tlt-java-courses commented on pom.xml
> +    <properties>
По моему я уже видел подобные изменения в прошлом ПР. Может стоит унифицировать в master ветке это дело?

2021-04-22 06:54 UTC, tlt-java-courses commented on src/main/java/com/epam/davydova/FileGenerator.java
> +        File file = new File("D:\\YandexDisk\\Repos\\src\\main\\resources\\Record.txt");
По изученным правилам CleanCode не должно быть в коде абсолютных путей от слова совсем. У меня сейчас не стратует программа из-за этого.

2021-04-22 06:54 UTC, tlt-java-courses commented on src/main/java/com/epam/davydova/Main.java
> +                new File("D:\\YandexDisk\\Repos\\src\\main\\resources\\Record.txt"));
И снова тот же путь. Если я поправлю в одном месте, мне необходимо искать его по всему проекту. Его нужно было делать константой.

2021-04-22 06:54 UTC, tlt-java-courses commented on src/main/java/com/epam/davydova/pojos/Cat.java
> +    public Cat() {
А зачем он нам пустой?

2021-04-22 06:54 UTC, tlt-java-courses commented on src/main/resources/Assignment.txt
> ++ Реализовать 2 POJO сущности
Лишний файл

2021-04-22 06:54 UTC, tlt-java-courses commented on src/main/resources/Record.txt
> +age=5
Зачем файл в проекте если он не используется

2021-04-22 06:54 UTC, tlt-java-courses commented on src/main/resources/Properties.txt
> +age=20
Зачем файл в проекте если он не используется

2021-04-22 06:54 UTC, tlt-java-courses commented on src/main/java/com/epam/davydova/pojos/Person.java
> +    @Value(destination = "D:\\YandexDisk\\Repos\\src\\main\\resources\\Record.txt")
В задании сказано: чтобы она дополнительно принимала путь **до значения** из txt файла
Т.е. путь НЕ до файла, а до значения в нём. У тебя переменная может называться в POJO как age, а в файле someExampleAge, и его мы должны подцепить.

2021-04-22 06:54 UTC, tlt-java-courses commented on src/main/java/com/epam/davydova/pojos/Person.java
> +    public Person() {
Зачем он нам пустой?

2021-04-22 06:54 UTC, tlt-java-courses commented on src/main/java/com/epam/davydova/annotations/Value.java
> +    String name() default "random";
А если я в сущность добавлю ещё с десяток полей, мне каждой нужно аннотацию обновлять?

2021-04-22 06:54 UTC, tlt-java-courses commented on src/main/java/com/epam/davydova/annotations/Value.java
> +public @interface Value {
JavaDoc?

2021-04-22 06:54 UTC, tlt-java-courses commented on src/main/java/com/epam/davydova/annotations/Entity.java
> +public @interface Entity {
JavaDoc?

2021-04-22 06:54 UTC, tlt-java-courses commented on src/main/java/com/epam/davydova/FileGenerator.java
> +        try (Scanner scanner = new Scanner(System.in);
Сканнер - круто, но давай без него? Обойдемся обычным считываним текста из файла.

2021-04-22 06:54 UTC, tlt-java-courses commented on src/main/java/com/epam/davydova/FileGenerator.java
> +                System.out.print("Type name = ");
Использование System.err и System.out

2021-04-22 06:54 UTC, tlt-java-courses commented on src/main/java/com/epam/davydova/FileGenerator.java
> +    private static final Logger logger = Logger.getLogger(FileGenerator.class.getName());
Лучше в логгер передавать класс, а не имя класса

2021-04-22 06:54 UTC, tlt-java-courses commented on src/main/java/com/epam/davydova/CheckPojos.java
> +    public static void checkEntityAnnotation(Class<?> object) {
Все методы класса статичные, хотя не являются утилитарными

2021-04-22 06:56 UTC, tlt-java-courses commented on src/main/java/com/epam/davydova/CheckPojos.java
> +import java.util.logging.Logger;
Давай испольовать логгеры из slf4j, а не встроенные в java

2021-04-22 06:56 UTC, tlt-java-courses commented on src/main/java/com/epam/davydova/CheckPojos.java
> +import java.util.logging.Logger;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

2021-04-24 04:04 UTC, DavydovaVV commented on pom.xml
> +    <properties>
Да, как раз сделала как надо, просто до этого была проблема с переходом с junit4 на junit5, были ошибки

2021-04-24 04:05 UTC, DavydovaVV commented on src/main/java/com/epam/davydova/FileGenerator.java
> +        File file = new File("D:\\YandexDisk\\Repos\\src\\main\\resources\\Record.txt");
сделала путь от source root

2021-04-24 04:07 UTC, DavydovaVV commented on src/main/java/com/epam/davydova/Main.java
> +                new File("D:\\YandexDisk\\Repos\\src\\main\\resources\\Record.txt"));
сделала константой, но, наверное, сейчас в этом нет необходимости, потому что он теперь только в одном месте

2021-04-24 04:09 UTC, DavydovaVV commented on src/main/java/com/epam/davydova/pojos/Cat.java
> +    public Cat() {
В pojo должен быть пустой конструктор, но раз он по дефолту есть, то отдельно его писать не надо, убрала

2021-04-24 04:09 UTC, DavydovaVV commented on src/main/resources/Assignment.txt
> ++ Реализовать 2 POJO сущности
Убрала

2021-04-24 04:10 UTC, DavydovaVV commented on src/main/resources/Record.txt
> +age=5
Он использовался. Я с консоли вводила данные, они записывались в этот файл, потом из этого файла считывались наборы полей. Сейчас его нет

2021-04-24 04:11 UTC, DavydovaVV commented on src/main/resources/Properties.txt
> +age=20
Этот тоже использовался, из него брались значения для заполнения полей, когда был не указан путь к файлу. Сейчас его нет

2021-04-24 04:12 UTC, DavydovaVV commented on src/main/java/com/epam/davydova/pojos/Person.java
> +    @Value(destination = "D:\\YandexDisk\\Repos\\src\\main\\resources\\Record.txt")
Сделала путь до значения

2021-04-24 04:12 UTC, DavydovaVV commented on src/main/java/com/epam/davydova/pojos/Person.java
> +    public Person() {
Тоже убрала

2021-04-24 04:12 UTC, DavydovaVV commented on src/main/java/com/epam/davydova/annotations/Value.java
> +    String name() default "random";
сделала по подсказке на лекции. Теперь value() и path()

2021-04-24 04:13 UTC, DavydovaVV commented on src/main/java/com/epam/davydova/annotations/Value.java
> +public @interface Value {
сделала. Думала, что у аннотаций не надо JavaDoc

2021-04-24 04:13 UTC, DavydovaVV commented on src/main/java/com/epam/davydova/annotations/Entity.java
> +public @interface Entity {
сделала

2021-04-24 04:14 UTC, DavydovaVV commented on src/main/java/com/epam/davydova/FileGenerator.java
> +        try (Scanner scanner = new Scanner(System.in);
Убрала, думала, что нужно генерировать значения в файл. Сканнер убрала. Теперь просто считывание из готового файла происходит

2021-04-24 04:14 UTC, DavydovaVV commented on src/main/java/com/epam/davydova/FileGenerator.java
> +                System.out.print("Type name = ");
Убрала

2021-04-24 04:14 UTC, DavydovaVV commented on src/main/java/com/epam/davydova/FileGenerator.java
> +    private static final Logger logger = Logger.getLogger(FileGenerator.class.getName());
В этом логгере надо имя класса, класс не принимает

2021-04-24 04:15 UTC, DavydovaVV commented on src/main/java/com/epam/davydova/CheckPojos.java
> +    public static void checkEntityAnnotation(Class<?> object) {
статики больше нет, т.к. они не утилитарные

2021-04-24 04:15 UTC, DavydovaVV commented on src/main/java/com/epam/davydova/CheckPojos.java
> +import java.util.logging.Logger;
сделала

2021-04-24 06:06 UTC, tlt-java-courses requested changes
Не достаточное тестовое покрытие. Рекомендую посмотреть отчет `target/jacoco-report/index.html`, чтобы понять какой кусок кода необходимо покрыть тестами.

2021-04-24 06:06 UTC, tlt-java-courses commented on src/main/java/com/epam/davydova/Main.java
> +    public static void main(String[] args) {
Не увидел демонстрации пунктов 3, 4.а, 4.b, 5

2021-04-24 06:06 UTC, tlt-java-courses commented on src/main/java/com/epam/davydova/pojos/Cat.java
> +@Entity
Убрал аннотацию, посыпались `java.lang.IllegalAccessException: null`, не по заданию.

2021-04-24 06:06 UTC, tlt-java-courses commented on src/main/resources/Properties.txt
> +age=2
Удалил файл, упала NPE. Не по заданию.

2021-04-24 13:04 UTC, DavydovaVV commented on src/test/java/com/epam/davydova/CheckPojosTest.java
> +class CheckPojosTest {
да, паблик, всегда забываю в тестах проставлять модификаторы.. Да, один тест, потому что этот метод тянет почти весь код, т.к. из него идут вызовы вдругих методов. Хотя я теперь думаю, что это скорее всего не очень правильно. Я постараюсь доделать покрытие.

2021-04-24 13:05 UTC, DavydovaVV commented on src/main/java/com/epam/davydova/Main.java
> +    public static void main(String[] args) {
Добавила демонстрацию. 
В пункте 4, я реализовала проверку на Value автоматически после проверки на Entity c кэтчем исключений, если будут. Поэтому в логе будет этот вывод ещё пару раз, т.к. я продублировала в Main, чтобы продемонстрировать. 
По пункту 5, к сигнатуре метода main добавлены необработанные исключения, потому что в классе с этими заполняющими сущность методами эти исключения обработывались в других методах, из которых они вызывались.

2021-04-24 13:08 UTC, DavydovaVV commented on src/main/java/com/epam/davydova/pojos/Cat.java
> +@Entity
Я в логгер добавила это, это словленные исключения, которые не прервали выполнение приложения (по заданию нужно было кинуть, если есть Value, но нет Entity). Заменила на только с объяснением того, что произошло. И сделала только один вывод этого сообщения, а не несколько

2021-04-24 13:08 UTC, DavydovaVV commented on src/main/resources/Properties.txt
> +age=2
Сейчас должно работать

2021-04-24 21:14 UTC, merged