Task1 and Task2, operations with streams
DavydovaVV/repo-java pull request #13
Opened 2021-04-28 18:14 UTC by DavydovaVV

Task1 и Task2, пока без тестов

2021-04-29 17:46 UTC, tlt-java-courses requested changes

2021-04-29 17:46 UTC, tlt-java-courses commented on src/main/java/com/epam/davydova/task1/FileProcessorWithStreams.java
> +        long number = stream.map(this::getSumOfUuidDigits).filter(integer -> integer > 100).count();
По клин коду цепочки вызовов нужно переносить
```
stream.map(this::getSumOfUuidDigits)
       .filter(integer -> integer > 100)
       .count();
```

2021-04-29 17:46 UTC, tlt-java-courses commented on src/main/java/com/epam/davydova/task1/FileProcessorWithStreams.java
> +        Stream<String> stream = Files.lines(Paths.get(PATH_TO_FILE_WITH_UUID));
А для чего тебе выносить в переменную это, можно ж было сразу обработать.

2021-04-29 17:46 UTC, tlt-java-courses commented on src/main/java/com/epam/davydova/task2/ObjectGenerator.java
> +    public void generateObject(Map<String, List<String>> mapOfDetails, Class<?> object) {
Думаю, можно было сделать проще. Считать строку, достать данные и просто просеттить ими новые объекты new Example(a, b, c)
А так, неплохо, ещё немного опыта с рефлексией.

2021-04-30 21:16 UTC, DavydovaVV commented on src/main/java/com/epam/davydova/task1/FileProcessorWithStreams.java
> +        long number = stream.map(this::getSumOfUuidDigits).filter(integer -> integer > 100).count();
Исправила

2021-04-30 21:17 UTC, DavydovaVV commented on src/main/java/com/epam/davydova/task1/FileProcessorWithStreams.java
> +        Stream<String> stream = Files.lines(Paths.get(PATH_TO_FILE_WITH_UUID));
Убрала лишние выводы переменных

2021-04-30 21:23 UTC, DavydovaVV commented on src/main/java/com/epam/davydova/task2/ObjectGenerator.java
> +    public void generateObject(Map<String, List<String>> mapOfDetails, Class<?> object) {
Я почему-то решила, что мне заранее могут быть неизвестны поля и что в POJO и в файл будут добавлять ещё какие-либо характеристики, поэтому решила через рефлексию. Переделала проще. 

Кстати, весь код пересмотрела, он у меня получился недружелюбным к тестированию, как и прошлый, в котором я всего одним методом почти весь код пробежала (в тот раз просто повезло, что получилось протестировать). Поняла в чем моя ошибка, исправила, надеюсь, лучше стало. Тестами все хорошо покрылось.

2021-04-30 21:51 UTC, DavydovaVV commented on src/main/java/com/epam/davydova/task2/ObjectGenerator.java
> +    public void generateObject(Map<String, List<String>> mapOfDetails, Class<?> object) {
Заметила странную вещь. В последнем коммите я исправила значения дат expectedResults в тестах для первого задания, но не потому что они были неправильными. В идее правильный ответ 2024-02-11, а здесь почему-то 2024-02-09. Вроде все посмотрела, где фейлит понять не могу.

2021-05-01 18:00 UTC, tlt-java-courses requested changes

2021-05-01 22:13 UTC, DavydovaVV commented on src/test/java/com/epam/davydova/task2/DetailWithForLoopTest.java
> +        Map<String, List<String>> mapOfDetails = detailWithForLoop.getDetails("src/main/resources/File.txt");
В константы вынесла имена файлов для тестовых классов, но не для классов проекта, т.к. иначе тест будет использовать файлы проекта

2021-05-01 22:24 UTC, DavydovaVV commented on src/test/java/com/epam/davydova/task2/DetailWithForLoopTest.java
> +        Map<String, List<String>> mapOfDetails = detailWithForLoop.getDetails("src/main/resources/File.txt");
и сделала отдельный пакет для ресурсов тестов

2021-05-02 20:23 UTC, tlt-java-courses approved these changes

2021-05-02 20:23 UTC, tlt-java-courses commented on src/main/java/com/epam/davydova/task1/FileProcessorWithStreams.java
> +            e.printStackTrace();
Логирование в catch блоке

2021-05-02 20:23 UTC, tlt-java-courses commented on src/main/java/com/epam/davydova/task1/interfaces/HashSetUuidFiller.java
> +    HashSet<UUID> uuidHashSet = new HashSet<>();
Переменных в интерфейсах лучше избегать

2021-05-02 20:23 UTC, tlt-java-courses commented on src/main/java/com/epam/davydova/task2/Sausage.java
> +    public Sausage(String type, int weight, long cost) {
Можно использовать lombok

2021-05-02 20:23 UTC, tlt-java-courses commented on src/test/java/com/epam/davydova/task1/FileProcessorWithForLoopTest.java
> +    FileProcessorWithForLoop processorWithForLoop = new FileProcessorWithForLoop();
private

2021-05-02 20:23 UTC, tlt-java-courses commented on src/main/java/com/epam/davydova/task2/DetailWithStream.java
> +        return Objects.requireNonNull(mapOfDetails);
Метод кинет NPE, что стоит избегать

2021-05-03 18:34 UTC, merged