Added modules: api, db, impl
DavydovaVV/repo-java pull request #15
Opened 2021-05-09 12:24 UTC by DavydovaVV

2021-05-09 12:30 UTC, tlt-java-courses requested changes

2021-05-09 12:30 UTC, tlt-java-courses commented on pom.xml
>      <groupId>groupId</groupId>
groupId не корректный

2021-05-09 12:36 UTC, tlt-java-courses requested changes

2021-05-09 12:36 UTC, tlt-java-courses commented on repo-java-api/pom.xml
> +        <groupId>groupId</groupId>
groupId дочерних модулей не соответствует родительскому

2021-05-09 12:36 UTC, tlt-java-courses commented on repo-java-db/pom.xml
> +        <groupId>groupId</groupId>
groupId дочерних модулей не соответствует родительскому

2021-05-09 12:36 UTC, tlt-java-courses commented on repo-java-impl/pom.xml
> +        <groupId>groupId</groupId>
groupId дочерних модулей не соответствует родительскому

2021-05-09 12:36 UTC, tlt-java-courses commented on pom.xml
> +                <groupId>com.epam.rd</groupId>
Зависимость на не существующий модуль. Данный проект даже не собрался бы

2021-05-09 12:36 UTC, tlt-java-courses commented on pom.xml
>      <artifactId>repo-java</artifactId>
Хорошо, если структура пакетов внутри проекта соответсвует groupId+artifactId сейчас же у тебя com.epam.rd.davydova. Давай приведм всё к одному

2021-05-09 12:48 UTC, DavydovaVV commented on pom.xml
>      <artifactId>repo-java</artifactId>
исправила, проект собрался

2021-05-09 13:18 UTC, DavydovaVV commented on pom.xml
>      <artifactId>repo-java</artifactId>
привела пакеты к виду groupId+artefactId

2021-05-10 14:46 UTC, tlt-java-courses requested changes

2021-05-10 14:46 UTC, tlt-java-courses commented on pom.xml
> +    <groupId>com.epam.rd.davydova</groupId>
```
<groupId>com.epam.rd</groupId>
<artifactId>davydova</artifactId>
```

2021-05-10 19:13 UTC, tlt-java-courses approved these changes

2021-05-10 19:13 UTC, merged