Task1 - changeLog + initial query to create schema and user
DavydovaVV/repo-java pull request #17
Opened 2021-05-20 08:41 UTC by DavydovaVV

2021-05-21 12:44 UTC, DavydovaVV commented on assignment-db/src/main/resources/epamcourses-changelog.xml
> +<?xml version="1.0" encoding="UTF-8"?>
переименовала

2021-05-21 12:44 UTC, DavydovaVV commented on assignment-db/src/main/resources/epamcourses-changelog.xml
> +<databaseChangeLog xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
сделано

2021-05-21 12:44 UTC, DavydovaVV commented on assignment-db/src/main/resources/epamcourses-changelog.xml
> +    <changeSet id="001" author="davydova">
выполнено

2021-05-22 13:16 UTC, tlt-java-courses requested changes

2021-05-22 13:16 UTC, tlt-java-courses commented on assignment-db/pom.xml
> +        <liquibase.user>user</liquibase.user>
Такого юзера у меня нет, из-за чего не могу создать схему. (не соответствует дз)

2021-05-22 13:16 UTC, tlt-java-courses commented on assignment-db/src/main/resources/master.sql
> +CREATE USER "user" WITH PASSWORD 'pass';
Некорректный юзер

2021-05-22 13:16 UTC, tlt-java-courses commented on assignment-impl/src/main/java/com/epam/rd/davydova/assignment/domain/entity/Customer.java
> +@Table(name = "Customer")
Аннотация точно нужна?

2021-05-22 13:16 UTC, tlt-java-courses commented on assignment-impl/src/main/java/com/epam/rd/davydova/assignment/domain/entity/Customer.java
> +    @OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
LAZY и так по дефолту

2021-05-22 13:16 UTC, tlt-java-courses commented on assignment-impl/src/main/java/com/epam/rd/davydova/assignment/domain/entity/Customer.java
> +@Table(name = "Customer")
В остальных энтитях аналогичный вопрос

2021-05-22 13:16 UTC, tlt-java-courses commented on assignment-impl/src/main/java/com/epam/rd/davydova/assignment/domain/entity/Customer.java
> +    @OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
В остальных энтитях аналогичное замечание

2021-05-22 15:24 UTC, DavydovaVV commented on assignment-db/pom.xml
> +        <liquibase.user>user</liquibase.user>
поменяла

2021-05-22 15:24 UTC, DavydovaVV commented on assignment-db/src/main/resources/master.sql
> +CREATE USER "user" WITH PASSWORD 'pass';
поменяла

2021-05-22 15:25 UTC, DavydovaVV commented on assignment-impl/src/main/java/com/epam/rd/davydova/assignment/domain/entity/Customer.java
> +@Table(name = "Customer")
убрала аннотации table, они не требуются в данном случае

2021-05-22 15:25 UTC, DavydovaVV commented on assignment-impl/src/main/java/com/epam/rd/davydova/assignment/domain/entity/Customer.java
> +    @OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
убрала лейзи фетч

2021-05-23 00:42 UTC, tlt-java-courses requested changes

2021-05-23 00:42 UTC, tlt-java-courses commented on assignment-impl/src/main/java/com/epam/rd/davydova/assignment/domain/entity/Customer.java
> +@Access(AccessType.FIELD)
Для чего эта аннотация?

2021-05-23 00:42 UTC, tlt-java-courses commented on assignment-impl/src/main/java/com/epam/rd/davydova/assignment/domain/entity/Customer.java
> +    public Customer(String customerName) {
Для чего конструктор?

2021-05-23 00:42 UTC, tlt-java-courses commented on assignment-impl/src/main/java/com/epam/rd/davydova/assignment/domain/entity/Customer.java
> +    @Column(name = "customer_id")
имя колонки в JPA автоматически преобразуется из lowerCamelCase в lower_snake_case. Поэтому в подобных случаях это указание излишнее

2021-05-23 20:07 UTC, tlt-java-courses approved these changes

2021-05-23 20:08 UTC, merged