Task 16:
DavydovaVV/repo-java pull request #22
Opened 2021-06-03 18:01 UTC by DavydovaVV

- Все сервисы переведены на бины
- EntityManager настроен в качестве бина
- Создан застабленный репозиторий в пакете "stub"(хардкод в файлах properties)
- Настроен профиль local для застабленного репозитория
- Настроен MessageSource
- Реализован перевод на RU и EN для entities из застабленного репозитория

2021-06-03 19:22 UTC, tlt-java-courses requested changes

2021-06-03 19:22 UTC, tlt-java-courses commented on assignment-impl/src/main/java/com/epam/rd/davydova/assignment/domain/service/CustomerService.java
> -import com.epam.rd.davydova.assignment.domain.entity.Customer;
В пакете domain должно быть только то, что можно назвать Entity и к ним относится. Сервисы и сервлеты должны находится в своих пакетах

2021-06-03 19:22 UTC, tlt-java-courses commented on assignment-impl/src/main/java/com/epam/rd/davydova/assignment/domain/service/CustomerService.java
>  public class CustomerService {
Интерфейс?

2021-06-03 19:22 UTC, tlt-java-courses commented on assignment-impl/src/main/java/com/epam/rd/davydova/assignment/domain/service/CustomerService.java
> +    public CustomerService(EntityManager entityManager) {
Давай использовать ломбок

2021-06-03 19:22 UTC, tlt-java-courses commented on assignment-impl/src/main/java/com/epam/rd/davydova/assignment/domain/service/CustomerService.java
> +    private EntityManager entityManager;
final

2021-06-03 19:22 UTC, tlt-java-courses commented on assignment-impl/src/main/java/com/epam/rd/davydova/assignment/domain/service/CustomerService.java
>      public void add(String customerName, String phone) {
Сервис - компонент слоя с бизнес логикой. Репозиторий - компонент работы с персистентным слоем, БД. Определись за что отвечает этот класс и реализуй недостающий.

2021-06-03 19:22 UTC, tlt-java-courses commented on assignment-impl/src/main/java/com/epam/rd/davydova/assignment/domain/service/OrderService.java
>  public class OrderService {
Аналогично предыдущему

2021-06-03 19:22 UTC, tlt-java-courses commented on assignment-impl/src/main/java/com/epam/rd/davydova/assignment/stub/model/Customer.java
> +public class Customer {
Стабать нужно источник данных, т.е. персистентный слой, а не сущности, сущность - просто данные

2021-06-04 05:11 UTC, DavydovaVV commented on assignment-impl/src/main/java/com/epam/rd/davydova/assignment/domain/service/CustomerService.java
> +    public CustomerService(EntityManager entityManager) {
использовала RequiredArgsConstructor, поле entityManager сделала final

2021-06-04 05:12 UTC, DavydovaVV commented on assignment-impl/src/main/java/com/epam/rd/davydova/assignment/domain/service/CustomerService.java
> +    private EntityManager entityManager;
сделано

2021-06-04 05:14 UTC, DavydovaVV commented on assignment-impl/src/main/java/com/epam/rd/davydova/assignment/domain/service/CustomerService.java
> -import com.epam.rd.davydova.assignment.domain.entity.Customer;
вынесла сервисы и сервлеты из пакета domain

2021-06-04 15:02 UTC, DavydovaVV commented on assignment-impl/src/main/java/com/epam/rd/davydova/assignment/domain/service/CustomerService.java
>  public class CustomerService {
сделала интерфейсы для сервисов

2021-06-04 15:03 UTC, DavydovaVV commented on assignment-impl/src/main/java/com/epam/rd/davydova/assignment/domain/service/CustomerService.java
>      public void add(String customerName, String phone) {
релизовала классы-репозитории для работы с бд, бизнес логика в сервисах.

2021-06-05 08:11 UTC, tlt-java-courses requested changes

2021-06-05 08:11 UTC, tlt-java-courses commented on assignment-impl/src/main/java/com/epam/rd/davydova/assignment/config/ComponentConfig.java
> +public class ComponentConfig {
В этом классе я вижу настройку бина entityManager. Предлагаюю класс назвать JpaConfig

2021-06-05 08:11 UTC, tlt-java-courses commented on assignment-impl/src/main/java/com/epam/rd/davydova/assignment/repository/impl/CustomerRepository.java
> +public class CustomerRepository implements ICustomerRepository {
Давай придерживаться более популярного наименования в Java. Где интерфесы просто CustomerRepository, а реализации CustomerRepositoryImpl

2021-06-05 08:11 UTC, tlt-java-courses commented on assignment-impl/src/main/java/com/epam/rd/davydova/assignment/repository/interfaces/ICustomerRepository.java
> +package com.epam.rd.davydova.assignment.repository.interfaces;
не нужно интерфесы в отдельный пакет пусть лежат себе в repository

2021-06-05 08:11 UTC, tlt-java-courses commented on assignment-impl/src/main/java/com/epam/rd/davydova/assignment/repository/interfaces/ICustomerRepository.java
> +    void save(Customer customer);
По хорошему репозитории должны возвращать результат сохранения в БД. Если я сохраню сущность и потом мне потребуется её id, где мне его взять?

2021-06-05 08:11 UTC, tlt-java-courses commented on assignment-impl/src/main/java/com/epam/rd/davydova/assignment/repository/interfaces/ICustomerRepository.java
> +    void update(Customer customer);
Тоже самое

2021-06-05 08:11 UTC, tlt-java-courses commented on assignment-impl/src/main/java/com/epam/rd/davydova/assignment/repository/interfaces/ICustomerRepository.java
> +    void delete(Customer customer);
Здесь множно boolean возвращать

2021-06-05 08:11 UTC, tlt-java-courses commented on assignment-impl/src/main/java/com/epam/rd/davydova/assignment/service/interfaces/ICustomerService.java
> +    void add(String customerName, String phone);
1. А если у кастомера будут заказы? А в будущем мы добавим ещё 2 десяятка полей? Проще в объект передавать саму сущность и данными из неё оперировать. 
2. Возвращать объект желательно иначе как оперировать обновленными данными?

2021-06-05 08:11 UTC, tlt-java-courses commented on assignment-impl/src/main/java/com/epam/rd/davydova/assignment/service/interfaces/ICustomerService.java
> +public interface ICustomerService {
Наименование

2021-06-05 08:11 UTC, tlt-java-courses commented on assignment-impl/src/main/java/com/epam/rd/davydova/assignment/service/interfaces/ICustomerService.java
> +package com.epam.rd.davydova.assignment.service.interfaces;
Пакет

2021-06-05 08:11 UTC, tlt-java-courses commented on assignment-impl/src/main/java/com/epam/rd/davydova/assignment/service/interfaces/ICustomerService.java
> +    void close();
В сервисе точно должен быть метод close? Что мы закрываем? Кастомера?

2021-06-05 08:12 UTC, tlt-java-courses requested changes
Тестовое покрытие

2021-06-05 13:12 UTC, DavydovaVV commented on assignment-impl/src/main/java/com/epam/rd/davydova/assignment/service/interfaces/ICustomerService.java
> +    void close();
Нет, этим методом я закрываю entity manager, я вынесла его в этот слой

2021-06-05 15:47 UTC, DavydovaVV commented on assignment-impl/src/main/java/com/epam/rd/davydova/assignment/service/interfaces/ICustomerService.java
> +    void add(String customerName, String phone);
1. аргументы методов оставила прежними, т.к hibernate не мог создать сессию почему-то и не мог найти persistence unit. Не смогла понять как это связано с тем, что я решила передавать в методы готовые объекты. Плюс не для всех методов хорошо сработало. Например, в Order пришлось создать дополнительное поле для продукта, т.к. до этого продукт передавался опосредованно (его id заносился в List).  Также создавать продукт сам по себе не очень удобно, т.к. цена за единицу имеет тип BigDecimal (нужно либо отдельно создавать BigDecimal, либо передавать в сервис product и цену за единицу). Т.е. уже нарушается единообразие аргументов в одинаковых методах для разных сервисов.
2. сделала возвраты из методов

2021-06-05 20:11 UTC, merged

2021-06-05 21:01 UTC, tlt-java-courses commented
1. Не выполняется апдейт скриптов миграции
![image](https://user-images.githubusercontent.com/75726498/120905250-e3beed00-c661-11eb-9570-3d43a6ce7f31.png)
2. Ошибка выполнения при запуске приложения
![image](https://user-images.githubusercontent.com/75726498/120905255-f802ea00-c661-11eb-8df4-e2274caebb34.png)
3. Методы репозиториев должны возвращать результат работы с БД на CRUD операциях 
![image](https://user-images.githubusercontent.com/75726498/120905302-4912de00-c662-11eb-986b-421a5fbed7e0.png)
4. Нерациональное оперирование данными. Добавим мы еще 3 десятка важных полей, их тоже в метод нужно передавать? 
![image](https://user-images.githubusercontent.com/75726498/120905354-824b4e00-c662-11eb-9ee0-78b615a55aa4.png)
5. Сервис влияет на закрытие сессии с БД. Смешение ответсвенности слоёв приложения.
![image](https://user-images.githubusercontent.com/75726498/120905376-a60e9400-c662-11eb-9ed0-29f890f49cd0.png)
6. Не бин
![image](https://user-images.githubusercontent.com/75726498/120905384-b757a080-c662-11eb-8d61-9a4d5c4922b2.png)
7. Нет тестов
8. Несоблюдение клин кода
8.1.  Лишний код
![image](https://user-images.githubusercontent.com/75726498/120905269-18cb3f80-c662-11eb-8a51-bd8338c681e2.png)
![image](https://user-images.githubusercontent.com/75726498/120905278-284a8880-c662-11eb-91f0-1c788418d018.png)
![image](https://user-images.githubusercontent.com/75726498/120905287-2ed90000-c662-11eb-8268-dfbe18a106ba.png)
8.2. JavaDocs